---
Title: BUAN 381 Final Project
Team: Brianna Floyd, Katie Luong, Anastasia Lomtadze, Sophia Saenger
---

Load libraries
```{r}
library(tidyverse)
```

Load data
```{r}
avaliacoes <- read_csv("https://raw.githubusercontent.com/katieluong33/BUAN-381/refs/heads/main/Avaliacoes.csv?token=GHSAT0AAAAAADCVIPOIXP23WL4G55OJC7ZE2AICPRA")
clientes <- read_csv("https://raw.githubusercontent.com/katieluong33/BUAN-381/refs/heads/main/Clientes.csv?token=GHSAT0AAAAAADCVIPOISCYAPXN55VHOCPWE2AICQJQ")
custos <- read_csv("https://raw.githubusercontent.com/katieluong33/BUAN-381/refs/heads/main/Custos_Operacionais.csv?token=GHSAT0AAAAAADCVIPOIAYKXHMRXMLW6Y3ZG2AICQSQ")
devolucoes <- read_csv("https://raw.githubusercontent.com/katieluong33/BUAN-381/refs/heads/main/Devolucoes.csv?token=GHSAT0AAAAAADCVIPOIE2F3QUDQ6IFDUJAI2AICQ2Q")
lojas <- read_csv("https://raw.githubusercontent.com/katieluong33/BUAN-381/refs/heads/main/Lojas.csv?token=GHSAT0AAAAAADCVIPOIG3DXUMLSLFYMHY7A2AICRCQ")
produtos <- read_csv("https://raw.githubusercontent.com/katieluong33/BUAN-381/refs/heads/main/Produtos.csv?token=GHSAT0AAAAAADCVIPOI7UAGFIVJCHXLEGTG2AICRJQ")
vendas <- read_csv("https://raw.githubusercontent.com/katieluong33/BUAN-381/refs/heads/main/Vendas.csv?token=GHSAT0AAAAAADCVIPOIQBG6AF7YYVDCFZGO2AICRQQ")
```

```{r}
# Start with Vendas and merge in other datasets step-by-step
full_data <- vendas %>%
  left_join(produtos, by = "Produto_ID") %>%
  left_join(clientes, by = "Cliente_ID") %>%
  left_join(avaliacoes, by = "Produto_ID") %>%
  left_join(devolucoes, by = "Produto_ID") %>%
  left_join(lojas, by = "Loja_ID") %>%
  left_join(custos, by = "Loja_ID")
```

```{r}
# Create new column for order price (regression target)
full_data <- full_data %>%
  mutate(Order_Price = Quantidade * Preco_Unitario)
```

